modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL="https://github.com/kyrptonaught/tooltipfix/issues"

[[mods]]
modId = "tooltipfix"
version = "${version}"
displayName = "ToolTip Fix"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tooltipfix"
logoFile="icon.png"
authors="kyrptonaught, jptrzy"
description = "Fixes ToolTips from running off the screen"

[[dependencies.tooltipfix]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tooltipfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
